
PreProc:
  Splitting:
    unsplit_data_root: 'data/data/unsplit_data/'
    split_data_root: 'data/data/split_data/'
    unsplit_dataset_path: 'data/data/unsplit_dataset.csv'
    split_pool_path: 'data/data/split_pool/'
  Segmenting:
    segmented_data_root: 'data/data/segmented_data/'
    segment_length : 10
